version: '1.0'
services:
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000

  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      # Opens port on the container
      - $MYSQL_DOCKER_PORT
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
# Names our volume
volumes:
  mysql-db:
